-- Enable vector support
create extension if not exists vector;

-- Scraped website content (knowledge base)
create table if not exists public.documents (
  id        bigint generated by default as identity primary key,
  content   text,
  metadata  jsonb,          -- e.g. {"lead_id": "abc123", "url": "..."}
  embedding vector(3072)    -- Gemini embedding size
);

-- Chat history
create table if not exists public.conversations (
  id         uuid primary key default gen_random_uuid(),
  session_id text not null,
  lead_id    text not null,
  role       text not null,   -- 'user' or 'assistant'
  content    text not null,
  created_at timestamptz default now()
);

create index if not exists conversations_session_idx
  on public.conversations (session_id, created_at);
create index if not exists conversations_lead_idx
  on public.conversations (lead_id);
